# Hopefully fixes whatever this is caused by: https://i.imgur.com/QLqYAn9.gifv
UpdateInventoryOnCancel: true

Items:

  # Unique name, does not matter what it is, as long as its unique.
  RottenCookie:

    # Permission to craft this item
    Permission: 'custom.food.rottencookie'

    # The Item that will be crafted.
    ResultItem:

      # Material of the item. List of all materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
      # If you want the output to be an item from mythic mobs, put "MI-<name of item in mythic mobs>" instead of the material.
      Material: COOKIE

      # The amount of items you get when crafting this
      Amount: 2

      # Name of the item
      Name: '&6Rotten Cookie'

      # Lore of the item
      Lore:
        - '&7Rot IX'

      # ENCHANTMENT,LEVEL List of all enchantments: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
      Enchantments:
        - 'DURABILITY,0'

      # ItemFlags. List of all ItemFlags: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
      ItemFlags:
        - 'HIDE_ENCHANTS'

    # Remove for shapeless recipe. Switch the Letters under ingredients with numbers instead of letters, for the amount.
    # Don't want the item to be craftable? Remove both Shape and Ingredients.
    Shape: ' C ,BAB, C '

    # Examples:
    # Shaped: A:PUMPKIN
    # Shapeless: 2:PUMPKIN
    #
    # If you want the shaped recipe to require more than 1 item in that specific slot, you do 'A:PUMPKIN:<AMOUNT>'
    # Example:
    # Shaped: A:PUMPKIN:5
    #
    # Using custom items in recipes:
    # Examples:
    # Shaped: 'A:CI-<ItemName>'
    # Shapeless: '2:CI-<ItemName>'
    # The custom item you use in the recipe has to be above the item which requires it in the config!
    #
    # If you want to use items from MythicMobs as an ingredient, same thing as with custom items, but MI- instead of CI-.
    #
    # For crafting with potions, you want to use POTION and CPOTION
    # POTION - used for vanilla potions. POTION:<amount>:<PotionType>:<Extended/Upgraded>
    # For example: POTION:1:NIGHT_VISION:EXTENDED
    #
    # CPOTION - Used for custom potions (specifically, it is intended for use with McMMO Potions.)
    # Usage: CPOTION:<amount>:<PotionEffectType>:<Duration>:<Amplifier>
    # For example: CPOTION:1:FAST_DIGGING:1800:1
    #
    # It will only read the first character before the first ":", so the plugin will read ABB:INK_SACK as A:INK_SACK
    Ingredients:
      - 'A:COCOA_BEANS'
      - 'B:WHEAT'
      - 'C:ROTTEN_FLESH'

    # List of actions for when the item is consumed.
    #
    # Available Actions:
    # Potion Effect: 'PE:<PotionEffectType>:<Duration In Ticks>:<Amplifier>' (Adds the specified potion effect to the player)
    # Cancel Event: 'CE' (Means the item does not get consumed, and does not restore hunger)
    # Extra Food: 'EF:<amount>' (The amount of extra food to restore)
    # Extra Saturation: 'ES:<amount>'
    # Remove Item: 'RI:<amount>' (If it fails to remove the item(s), all effects AFTER this is in the list will not be triggered.)
    # Particle Trail: 'PT:<Particle>:<ParticleAmount>:<OffsetX>:<OffsetY>:<OffsetZ>:<Delay>:<Optional: TimesToPlay>' (Don't include TimesToPlay for it to run until the player reactivates the item, or leaves the server.)
    # Effect Trail: 'ET:<Effect>:<Data>:<OffsetX>:<OffsetY>:<OffsetZ>:<Delay>'
    # Message Player: 'MP:<Message>' (Placeholders: %player% for the player name.)
    # Dispatch Command: 'DC:<console true/false>:<command>' (Placeholders: %player& for the player name.)
    # Play Sound: 'PS:<Sound>:<Volume>:<Pitch>'
    #
    # Plugins Hooks:
    # Brewery Remove Drunkenness: 'RD:<amount>:<show drunkenness>' (Removes <amount> of drunkenness from the player, if Brewery is present and the player is drunk. Show drunkenness defaults to true if its not present)
    #
    # Potion Effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
    # Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    # Particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    # Effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.htm
    #
    # You can use as many particle and effect trails as you want per item,
    # but you can only have 1 item active at time.
    #
    # Most of the actions can also be delayed, except Cancel Event. Set up like this: '<Action Prefix>-<Wanted Delay In Ticks>:<rest of the action>'
    # Example: 'PE-2:SLOW:200:0' delays the giving of potion effect SLOW by 2 ticks.
    OnConsume:
      - 'PE:CONFUSION:200:0'
      - 'PE:SLOW:100:0'
      - 'CE'
      - 'EF:2'
      - 'ES:1'
    # Same as OnConsume, except when you click while holding the item instead of eat.
    OnClick:
      - 'PE:SLOW:300:1'
      - 'PE:CONFUSION:200:0'
  BetterCookie:
    Permission: 'custom.food.bettercookie'
    ResultItem:
      Material: COOKIE
      Amount: 2
      Name: '&6Better Cookie'
      Lore:
        - '&7Eatable II'
      Enchantments:
        - 'DURABILITY,0'
      ItemFlags:
        - 'HIDE_ENCHANTS'
    Shape: 'BAB'
    Ingredients:
      - 'A:MILK_BUCKET'
      - 'B:CI-RottenCookie'
    OnConsume:
      - 'PE:SPEED:200:0'
      - 'EF:6'
      - 'ES:6'

Messages:
  NoPermission: "&4You do not have permission to do that."
  UnknownCommand: "&4Unknown command. Try /citems for a list of commands."
  Commands:
    ItemError: "&cThat item does not exist."
    NotANumber: "&cThat's not a number."
    Received: "&aYou've received %amount% %item%"
    ReceivedFull: "&cYou've received %amount% %item%, but your inventory was full so it was dropped instead."
    List:
      Items: "&aAvailable Items:"
    Get:
      Usage: "&cIncorrect usage. Try: /citem get <item name> <amount>"
    Give:
      Usage: "&cIncorrect usage. Try: /citem give <player> <item name> <amount>"
      NotOnline: "&c%player% is not online."
      Success: "&a%player% has received %amount% %item%"
    Help:
      - "&aCommands:"
      - "&a/citem get <item> <amount> &7- Gives you <amount> of <item>"
      - "&a/citem give <player> <item> <amount> &7- Gives an item to player."
      - "&a/citem list &7- Lists all items"
    View:
      Usage: "&cIncorrect command usage. try /citem view <item name>"
      NoRecipe: "&cThere's no item with that name, or the item does not have a recipe."
    Reload: "&aAttempting to reload recipes."